# Generated by Django 5.0.7 on 2024-07-10 04:04

import core.models
import stdimage.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Imovel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('Casa', 'Casa'), ('Apartamento', 'Apartamento'), ('Terreno', 'Terreno')], max_length=20, verbose_name='Tipo de Imóvel')),
                ('rua', models.CharField(max_length=100, verbose_name='Rua')),
                ('numero', models.CharField(max_length=10, verbose_name='Número')),
                ('bairro', models.CharField(max_length=100, verbose_name='Bairro')),
                ('cidade', models.CharField(max_length=100, verbose_name='Cidade')),
                ('estado', models.CharField(max_length=2, verbose_name='Estado')),
                ('cep', models.CharField(max_length=8, verbose_name='CEP')),
                ('num_quartos', models.PositiveIntegerField(verbose_name='Número de Quartos')),
                ('num_banheiros', models.PositiveIntegerField(verbose_name='Número de Banheiros')),
                ('num_garagem', models.PositiveIntegerField(verbose_name='Número de Vagas na Garagem')),
                ('pets', models.BooleanField(default=False, verbose_name='Aceita Pets')),
                ('condicoes', models.CharField(choices=[('Novo', 'Novo'), ('Usado', 'Usado'), ('Reformado', 'Reformado'), ('Antigo', 'Antigo'), ('Em reforma', 'Em reforma')], max_length=20, verbose_name='Condições')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('imagem', stdimage.models.StdImageField(force_min_size=False, upload_to=core.models.get_file_path, variations={'thumb': {'crop': True, 'height': 480, 'width': 480}}, verbose_name='Imagem')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Imóvel',
                'verbose_name_plural': 'Imóveis',
            },
        ),
    ]
