# Generated by Django 5.0.7 on 2024-07-10 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imovel',
            name='data_atualizacao',
        ),
        migrations.RemoveField(
            model_name='imovel',
            name='data_criacao',
        ),
    ]
