# Generated by Django 5.0.7 on 2024-07-10 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_imovel_data_atualizacao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='imovel',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='descricao',
            field=models.TextField(blank=True, verbose_name='Descrição'),
        ),
    ]
