# Generated by Django 5.0.7 on 2024-07-12 17:33

import core.models
import stdimage.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_imovel_slug_alter_imovel_descricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='imovel',
            name='agenda',
            field=models.CharField(default='', max_length=100, verbose_name='Agenda'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='imovel',
            name='imagem',
            field=stdimage.models.StdImageField(blank=True, force_min_size=False, upload_to=core.models.get_file_path, variations={'thumb': {'crop': True, 'height': 480, 'width': 480}}, verbose_name='Imagem'),
        ),
    ]
