# Generated by Django 5.0.7 on 2024-07-12 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_imovel_agenda_alter_imovel_imagem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imovel',
            name='descricao',
        ),
        migrations.RemoveField(
            model_name='imovel',
            name='imagem',
        ),
        migrations.AlterField(
            model_name='imovel',
            name='slug',
            field=models.SlugField(allow_unicode=True, max_length=200, unique=True),
        ),
    ]
