# Generated by Django 5.0.7 on 2024-07-12 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_imovel_descricao_remove_imovel_imagem_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imovel',
            name='agenda',
        ),
        migrations.AddField(
            model_name='imovel',
            name='proprietario',
            field=models.CharField(default='', max_length=100, verbose_name='Proprietário'),
            preserve_default=False,
        ),
    ]
