# Generated by Django 5.0.7 on 2024-07-12 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_imovel_agenda_imovel_proprietario'),
    ]

    operations = [
        migrations.AddField(
            model_name='imovel',
            name='agenda',
            field=models.CharField(choices=[('Aguardando cliente', 'aguardando cliente'), ('Agendamento concluído', 'agendamento feito'), ('Agendamento cancelado', 'agendamento cancelado')], default='', max_length=100, verbose_name='Agenda'),
            preserve_default=False,
        ),
    ]
