# Generated by Django 5.0.7 on 2024-07-12 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_imovel_agenda'),
    ]

    operations = [
        migrations.AddField(
            model_name='imovel',
            name='descricao',
            field=models.TextField(default='', verbose_name='Descrição'),
            preserve_default=False,
        ),
    ]
