# Generated by Django 5.0.7 on 2024-07-12 23:39

import core.models
import stdimage.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_imovel_descricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='imovel',
            name='imagem',
            field=stdimage.models.StdImageField(default='', force_min_size=False, upload_to=core.models.get_file_path, variations={'thumb': {'crop': True, 'height': 480, 'width': 480}}, verbose_name='Imagem'),
            preserve_default=False,
        ),
    ]
